//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInfo
    {
        public int fInfoId { get; set; }
        public Nullable<System.DateTime> f日期 { get; set; }
        public string f作業通知 { get; set; }
        public string f用品通知 { get; set; }
        public string f其他通知 { get; set; }
        public Nullable<int> fClassId { get; set; }
    }
}
