//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tStudent()
        {
            this.tCommunications = new HashSet<tCommunication>();
            this.tDiaries = new HashSet<tDiary>();
        }
    
        public int f學生編號 { get; set; }
        public string f學生姓名 { get; set; }
        public Nullable<System.DateTime> f學生生日 { get; set; }
        public string f學生密碼 { get; set; }
        public Nullable<bool> f學生性別 { get; set; }
        public Nullable<int> fClassId { get; set; }
        public string f身份區分 { get; set; }
        public Nullable<int> f家庭編號 { get; set; }

        [JsonIgnore]
        public virtual tClass tClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tCommunication> tCommunications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tDiary> tDiaries { get; set; }
        [JsonIgnore]
        public virtual tParent tParent { get; set; }
    }
}
