//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTeacher
    {
        public int f老師編號 { get; set; }
        public string f老師姓名 { get; set; }
        public Nullable<System.DateTime> f老師生日 { get; set; }
        public string f老師密碼 { get; set; }
        public Nullable<bool> f老師性別 { get; set; }
        public string f身份區分 { get; set; }
    }
}
