//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTotal
    {
        public string f學級年度 { get; set; }
        public string f年級 { get; set; }
        public string f班級 { get; set; }
        public Nullable<int> f學生編號 { get; set; }
        public string f座號 { get; set; }
        public string f學生姓名 { get; set; }
        public Nullable<int> f老師編號 { get; set; }
        public string f導師姓名 { get; set; }
        public string f帳號 { get; set; }
        public string f密碼 { get; set; }
        public string f身份區分 { get; set; }
        public string f班級課表 { get; set; }
        public string f授課課表 { get; set; }
        public Nullable<System.DateTime> f日期 { get; set; }
        public string f作業通知 { get; set; }
        public string f用品通知 { get; set; }
        public string f其他通知 { get; set; }
        public string f推播通知 { get; set; }
        public string f學生日誌照片 { get; set; }
        public string f學生日誌文字 { get; set; }
        public string f日誌批改 { get; set; }
        public string f家長交代事項 { get; set; }
        public string f老師交代事項 { get; set; }
        public Nullable<bool> f家長簽章 { get; set; }
        public Nullable<bool> f導師簽章 { get; set; }
        public Nullable<bool> f性別 { get; set; }
        public string f生日 { get; set; }
        public Nullable<int> fClassId { get; set; }
    }
}
